name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python 3.12.2
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Install PlatformIO Core
        run: pip install platformio

      - name: Build Tomo firmware
        run: python -m platformio run